# -*- coding: utf-8 -*-
"""centigrados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_pThzOsOsZhUk2o7-PGzYTXEnA97YSuw
"""

class Meteorologia:
    def __init__(self):
        self.temp = [80, 72, 95, 82, 79, 72, 85]

    def convertir_a_centigrados(self):
        centigrados = []
        for f in self.temp:
            c = (f - 32) * 5 / 9
            centigrados.append(round(c, 2))
        return centigrados

    def mostrar(self):
        print("Temperaturas en Fahrenheit:")
        print(self.temp)
        print("Temperaturas en Centígrados:")
        print(self.convertir_a_centigrados())

estacion = EstacionMeteorologica()
estacion.mostrar()