# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ts9HeoywRAw8f_xaK1w8__53kNNLjQwz
"""

alumno = {
    'nombre': "Camila Sepúlveda",
    'matricula': "231960258-0",
    'edad': 17,
    'peso': 50,
    'telefono': "3111009392",
    'domicilio': "Av. Allende",
    'carrera': "cdia"
}

print(alumno)


alumno['nombre'] = "Daniela Huerta"
print("nombre modificado:", alumno['nombre'])
alumno['matricula'] = "231690367-9"
print("matricula modificada:", alumno['matricula'])
alumno['edad'] = 16
print("edad modificada:", alumno['edad'])
alumno['peso'] = 55
print("peso modificado:", alumno['peso'])
alumno['telefono'] = "311 234 5678"
print("telefono modificado:", alumno['telefono'])
alumno['domicilio'] = "Pedregal"
print("domicilio modificado:", alumno['domicilio'])
alumno['carrera'] = "gastronomia"
print("carrera modificada:", alumno['carrera'])

alumno.pop('peso')
print("dato eliminado - peso")

for clave, valor in alumno.items():
    print(f"{clave}: {valor}")
print()

print(" Diccionario final ")
print(alumno)